export { default as NavBar } from "./NavBar";
export { default as TextData } from "./TextData";
export { default as Crousel } from "./Crousel";
export { default as CrouselCard } from "./CrouselCard";
export { default as Boxes } from "./Boxes";
export { default as SupportNBusiness } from "./SupportNBusiness";
export { default as GotoTop } from "./GotoTop";
export { default as Footer } from "./Footer";
export { default as OurServices } from "./OurServices";