import React from "react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Footer, GotoTop, NavBar } from "./components";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Guru Goutam Infotech Private Limited",
  description: "Generated by Imran",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
          <NavBar />
          <main>{children}</main>
          <Footer />
          <GotoTop /> {/* upIcon Here */}
      </body>
    </html>
  );
}





